[versions]
agp = "8.0.2"
kotlin = "1.9.0"
xposed-api = "100"
xposed-service = "100-1.0.0"

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
libxposed-api = { group = "io.github.libxposed", name = "api", version.ref = "xposed-api" }
libxposed-service = { group = "io.github.libxposed", name = "service", version.ref = "xposed-service" }
